import {
  User,
  Users,
  Server,
  Lock,
  // Tool,
  UserPlus,
  Trash2,
  Home,
  Info,
  Briefcase,
} from "react-feather";
import { Settings } from "feather-icons-react/build/IconComponents";

export const all_routes = {
  base_path: "/",
  signin: "/signin",
  forgotPassword: "/forgot-password",
  resetpassword: "/reset-password/:token",
  verifyToken: "/verify-token",
  verifyTokenTwo: "/verify-token/:type",
  headers: [
    {
      id: 1,
      name: "dashboard",
      path: "/dashboard",
      icon: Home,
      text: "Dashboard",
      permission: "read",
    },
    {
      id: 2,
      module: "contacts",
      name: "Contacts",
      path: "/contacts",
      icon: Users,
      text: "Contacts",
      permission: "read",
    },
    {
      id: 3,
      module: "matters",
      name: "Matters",
      path: "/matters",
      icon: Briefcase,
      text: "Matters",
      permission: "read",
    },
  ],
  addContact: {
    module: "contacts",
    name: "addContact",
    path: "/contacts/add",
    icon: UserPlus,
    text: "New",
    permission: "create",
  },
  editContact: {
    module: "contacts",
    name: "editContact",
    path: "/contacts/:contactId/edit",
    icon: User,
    text: "Edit Contact",
    permission: "update",
  },
  settings: [
    {
      id: 1,
      name: "personal-settings-group",
      path: "/settings/personal",
      icon: Settings,
      text: "Personal Settings",
      permission: "read",
      children: [
        {
          id: 1,
          name: "personal-settings",
          path: "/settings/personal",
          icon: User,
          text: "Personal Settings",
          permission: "read",
        },
        {
          id: 2,
          name: "security-settings",
          path: "/settings/security",
          icon: Lock,
          text: "Security & Password",
          permission: "read",
        },
        // {
        //   id: 3,
        //   name: "company-settings",
        //   path: "/settings/company",
        //   icon: Tool,
        //   text: "Company Settings",
        //   permission: "read",
        // },
        {
          id: 4,
          name: "firm-logo-info-settings",
          path: "/settings/firm-logo-info",
          icon: Info,
          text: "Firm Logo & Info",
          permission: "read",
        },
        // {
        //   id: 5,
        //   name: "client-portal-logo-colors-settings",
        //   path: "/settings/client-portal-logo-colors",
        //   icon: Settings,
        //   text: "Client Portal Logo Colors",
        //   permission: "read",
        // },
        // {
        //   id: 6,
        //   name: "custom-fields-settings",
        //   path: "/settings/custom-fields",
        //   icon: FileText,
        //   text: "Custom Fields",
        //   permission: "read",
        // },
        // {
        //   id: 7,
        //   name: "tags-settings",
        //   path: "/settings/tags",
        //   icon: Tag,
        //   text: "Tags",
        //   permission: "read",
        // },
        // {
        //   id: 8,
        //   name: "e-signature-settings",
        //   path: "/settings/e-signature",
        //   icon: FileText,
        //   text: "E-Signature",
        //   permission: "read",
        // },
        // {
        //   id: 9,
        //   name: "text-messaging-settings",
        //   path: "/settings/text-messaging",
        //   icon: MessageCircle,
        //   text: "Text Messaging",
        //   permission: "read",
        // },
        {
          id: 10,
          name: "recycle-bin-settings",
          path: "/settings/recycle-bin",
          icon: Trash2,
          text: "Recycle Bin",
          permission: "read",
        },
      ],
    },
    // {
    //   id: 2,
    //   name: "invoices-and-payments-group",
    //   path: "/settings/online-payments",
    //   icon: Archive,
    //   text: "Invoices & Payments",
    //   permission: "read",
    //   children: [
    //     {
    //       id: 1,
    //       name: "custom-hourly-rates-settings",
    //       path: "/settings/online-payments",
    //       icon: CreditCard,
    //       text: "Custom Hourly Rates",
    //       permission: "read",
    //     },
    //     {
    //       id: 2,
    //       name: "email-templates-settings",
    //       path: "/settings/email-templates",
    //       icon: Mail,
    //       text: "Email Templates",
    //       permission: "read",
    //     },
    //     {
    //       id: 3,
    //       name: "invoice-options-settings",
    //       path: "/settings/invoice-options",
    //       icon: FileText,
    //       text: "Invoice Options",
    //       permission: "read",
    //     },
    //   ],
    // },
    {
      id: 2,
      name: "user-settings-group",
      path: "/settings/users",
      icon: Server,
      text: "User Settings",
      permission: "read",
      children: [
        {
          id: 1,
          name: "user-groups-settings",
          path: "/settings/users",
          icon: UserPlus,
          text: "Users",
          permission: "read",
        },
        // {
        //   id: 2,
        //   name: "user-roles-settings",
        //   path: "/settings/user-groups",
        //   icon: Users,
        //   text: "User Groups",
        //   permission: "read",
        // },
        {
          id: 3,
          name: "roles-permissions-settings",
          path: "/settings/roles-permissions",
          icon: Lock,
          text: "Roles & Permissions",
          permission: "read",
        },
      ],
    },
  ],
  editRolePermission: "/settings/roles-permissions/:roleId/edit",
  addRolePermission: "/settings/roles-permissions/add",
  addUser: "/settings/users/add",
  editUser: "/settings/users/:userId/edit",
  error404: "/error-404",
  error500: "/error-500",
  comingsoon: "/coming-soon",
  undermaintenance: "/under-maintenance",
};
