import {
  User,
  Users,
  Server,
  Lock,
  // Tool,
  Clock,
  UserPlus,
  Trash2,
  Home,
  Info,
  FileText,
  Tag,
  Briefcase,
  CreditCard,
} from "react-feather";
import {
  EventAvailableOutlined,
  EventRepeatOutlined,
} from "@mui/icons-material";
import { Settings } from "feather-icons-react/build/IconComponents";

export const all_routes = {
  base_path: "/",
  signin: "/signin",
  forgotPassword: "/forgot-password",
  resetpassword: "/reset-password/:token",
  verifyToken: "/verify-token",
  verifyTokenTwo: "/verify-token/:type",
  headers: [
    {
      id: 1,
      module: "dashboard",
      name: "dashboard",
      path: "/dashboard",
      icon: Home,
      text: "Dashboard",
      permission: "read",
    },
    // {
    //   id: 2,
    //   module: "manage_contacts",
    //   name: "Contacts",
    //   path: "/contacts",
    //   icon: Users,
    //   text: "Contacts",
    //   permission: "read",
    // },
    // {
    //   id: 3,
    //   module: "manage_matters",
    //   name: "Matters",
    //   path: "/matters",
    //   icon: Briefcase,
    //   text: "Matters",
    //   permission: "read",
    // },
    // {
    //   id: 4,
    //   module: "manage_time_entries",
    //   name: "Time Entries",
    //   path: "/time-entries",
    //   icon: Clock,
    //   text: "Time Entries",
    //   permission: "read",
    // },
    // {
    //   id: 5,
    //   module: "manage_billings_and_invoices",
    //   name: "Billings and Invoices",
    //   path: "#",
    //   icon: CreditCard,
    //   text: "Billings and Invoices",
    //   permission: "read",
    //   children: [
    //     {
    //       id: 1,
    //       module: "manage_billings_and_invoices",
    //       name: "Billings and Invoices",
    //       path: "/billings-and-invoices",
    //       icon: CreditCard,
    //       text: "Invoices",
    //       permission: "read",
    //     },
    //     {
    //       id: 2,
    //       module: "manage_billings_and_invoices_expenses",
    //       name: "expenses",
    //       path: "/billings-and-invoices/expenses",
    //       icon: CreditCard,
    //       text: "Expenses",
    //       permission: "read",
    //     },
    //     {
    //       id: 3,
    //       module: "manage_billings_and_invoices_flat_fees",
    //       name: "flat fees",
    //       path: "/billings-and-invoices/flat-fees",
    //       icon: CreditCard,
    //       text: "Flat Fees",
    //       permission: "read",
    //     },
    //     {
    //       id: 4,
    //       module: "manage_billings_and_invoices_categories",
    //       name: "categories",
    //       path: "/billings-and-invoices/categories",
    //       icon: FileText,
    //       text: "Categories",
    //       permission: "read",
    //     },
    //     {
    //       id: 5,
    //       module: "manage_billings_and_invoices_items",
    //       name: "items",
    //       path: "/billings-and-invoices/items",
    //       icon: Tag,
    //       text: "Items",
    //       permission: "read",
    //     },
    //   ],
    // },
  ],
  addContact: {
    module: "manage_contacts",
    name: "addContact",
    path: "/contacts/add",
    icon: UserPlus,
    text: "New",
    permission: "create",
  },
  editContact: {
    module: "manage_contacts",
    name: "editContact",
    path: "/contacts/:contactId/edit",
    icon: User,
    text: "Edit Contact",
    permission: "update",
  },
  contactDetails: {
    module: "manage_contacts",
    name: "contactDetails",
    path: "/contacts/:contactId/details",
    icon: User,
    text: "Contact Details",
    permission: "read",
  },
  contactMatters: {
    module: "manage_contacts",
    name: "contactMatters",
    path: "/contacts/:contactId/matters",
    icon: Briefcase,
    text: "Contact Matters",
    permission: "read",
  },
  addMatter: {
    module: "manage_matters",
    name: "addMatter",
    path: "/matters/add",
    icon: Briefcase,
    text: "New",
    permission: "create",
  },
  editMatter: {
    module: "manage_matters",
    name: "editMatter",
    path: "/matters/:matterId/edit",
    icon: Briefcase,
    text: "Edit",
    permission: "update",
  },
  matterDetails: {
    module: "manage_matters",
    name: "matterDetails",
    path: "/matters/:matterId/details",
    icon: Briefcase,
    text: "Matter Details",
    permission: "read",
  },
  addTimeEntry: {
    module: "manage_time_entries",
    name: "addTimeEntry",
    path: "/time-entries/add",
    icon: Clock,
    text: "New",
    permission: "create",
  },
  multipleTimeEntries: {
    module: "manage_time_entries",
    name: "multipleTimeEntries",
    path: "/time-entries/multiple",
    icon: Clock,
    text: "Multiple Time Entries",
    permission: "create",
  },
  addInvoice: {
    module: "manage_billings_and_invoices",
    name: "addInvoice",
    path: "/billings-and-invoices/add",
    icon: CreditCard,
    text: "New",
    permission: "create",
  },
  editInvoice: {
    module: "manage_billings_and_invoices",
    name: "editInvoice",
    path: "/billings-and-invoices/:invoiceId/edit",
    icon: CreditCard,
    text: "Edit",
    permission: "update",
  },
  addExpense: {
    module: "manage_billings_and_invoices_expenses",
    name: "addExpense",
    path: "/billings-and-invoices/expenses/add",
    icon: CreditCard,
    text: "New",
    permission: "create",
  },
  editExpense: {
    module: "manage_billings_and_invoices_expenses",
    name: "editExpense",
    path: "/billings-and-invoices/expenses/:expenseId/edit",
    icon: CreditCard,
    text: "Edit",
    permission: "update",
  },
  addFlatFee: {
    module: "manage_billings_and_invoices_flat_fees",
    name: "addFlatFee",
    path: "/billings-and-invoices/flat-fees/add",
    icon: CreditCard,
    text: "New",
    permission: "create",
  },
  editFlatFee: {
    module: "manage_billings_and_invoices_flat_fees",
    name: "editFlatFee",
    path: "/billings-and-invoices/flat-fees/:flatFeeId/edit",
    icon: CreditCard,
    text: "Edit",
    permission: "update",
  },
  settings: [
    {
      id: 1,
      module: "user_profile",
      name: "personal-settings-group",
      path: "/settings/personal",
      icon: Settings,
      text: "Personal Settings",
      permission: "update",
      children: [
        {
          id: 1,
          module: "user_profile",
          name: "personal-settings",
          path: "/settings/personal",
          icon: User,
          text: "Personal Settings",
          permission: "update",
        },
        {
          id: 2,
          module: "user_profile",
          name: "security-settings",
          path: "/settings/security",
          icon: Lock,
          text: "Security & Password",
          permission: "update",
        },
        // {
        //   id: 3,
        //   name: "company-settings",
        //   path: "/settings/company",
        //   icon: Tool,
        //   text: "Company Settings",
        //   permission: "read",
        // },
        {
          id: 4,
          module: "manage_profile",
          name: "firm-logo-info-settings",
          path: "/settings/firm-logo-info",
          icon: Info,
          text: "Firm Logo & Info",
          permission: "update",
        },
        // {
        //   id: 5,
        //   name: "client-portal-logo-colors-settings",
        //   path: "/settings/client-portal-logo-colors",
        //   icon: Settings,
        //   text: "Client Portal Logo Colors",
        //   permission: "read",
        // },
        // {
        //   id: 6,
        //   name: "custom-fields-settings",
        //   path: "/settings/custom-fields",
        //   icon: FileText,
        //   text: "Custom Fields",
        //   permission: "read",
        // },
        // {
        //   id: 7,
        //   name: "tags-settings",
        //   path: "/settings/tags",
        //   icon: Tag,
        //   text: "Tags",
        //   permission: "read",
        // },
        // {
        //   id: 8,
        //   name: "e-signature-settings",
        //   path: "/settings/e-signature",
        //   icon: FileText,
        //   text: "E-Signature",
        //   permission: "read",
        // },
        // {
        //   id: 9,
        //   name: "text-messaging-settings",
        //   path: "/settings/text-messaging",
        //   icon: MessageCircle,
        //   text: "Text Messaging",
        //   permission: "read",
        // },
        {
          id: 10,
          module: "manage_recyclebin",
          name: "recycle-bin-settings",
          path: "/settings/recycle-bin",
          icon: Trash2,
          text: "Recycle Bin",
          permission: "read",
        },
      ],
    },
    {
      id: 2,
      module: "manage_users",
      name: "user-settings-group",
      path: "/settings/users",
      icon: Server,
      text: "Team Members Settings",
      permission: "read",
      children: [
        {
          id: 1,
          module: "manage_users",
          name: "user-groups-settings",
          path: "/settings/users",
          icon: UserPlus,
          text: "Team Members",
          permission: "read",
        },
        {
          id: 3,
          module: "manage_users_role",
          name: "roles-permissions-settings",
          path: "/settings/roles-permissions",
          icon: Lock,
          text: "Roles & Permissions",
          permission: "read",
        },
      ],
    },
    {
      id: 3,
      module: "manage_subscriptions",
      name: "subscriptions-settings-group",
      path: "/settings/subscriptions",
      icon: EventAvailableOutlined,
      text: "Subscriptions",
      permission: "read",
      children: [
        {
          id: 1,
          module: "manage_subscriptions",
          name: "subscriptions-settings",
          path: "/settings/subscriptions",
          icon: EventRepeatOutlined,
          text: "Subscriptions",
        },
      ],
    },
  ],
  editRolePermission: {
    module: "manage_users_role",
    name: "editRolePermission",
    path: "/settings/roles-permissions/:roleId/edit",
    icon: Lock,
    text: "Edit Role & Permission",
    permission: "update",
  },
  editUserPermissions: {
    module: "manage_users_role",
    name: "editUserPermissions",
    path: "/settings/users/:userId/permissions",
    icon: Lock,
    text: "Edit User Permissions",
    permission: "update",
  },
  addRolePermission: {
    module: "manage_users_role",
    name: "addRolePermission",
    path: "/settings/roles-permissions/add",
    icon: Lock,
    text: "Add",
    permission: "create",
  },

  addUser: {
    module: "manage_users",
    name: "addUser",
    path: "/settings/users/add",
    icon: UserPlus,
    text: "Add Team Member",
    permission: "create",
  },

  editUser: {
    module: "manage_users",
    name: "editUser",
    path: "/settings/users/:userId/edit",
    icon: User,
    text: "Edit Team Member",
    permission: "update",
  },

  userDetails: {
    module: "manage_users",
    name: "userDetails",
    path: "/settings/users/:userId/details",
    icon: User,
    text: "Team Member Details",
    permission: "read",
  },

  error404: "/error-404",
  error500: "/error-500",
  comingsoon: "/coming-soon",
  undermaintenance: "/under-maintenance",
};
